In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [17]:
tf.__version__

'2.2.0'

In [18]:
dataset = pd.read_csv('/content/drive/My Drive/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [21]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [24]:
ann = tf.keras.models.Sequential()

In [25]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [27]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [28]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [29]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6327 - accuracy: 0.6685
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4980 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4545 - accuracy: 0.8010
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4374 - accuracy: 0.8065
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4294 - accuracy: 0.8109
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4240 - accuracy: 0.8155
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4196 - accuracy: 0.8199
Epoch 8/100
250/250 [==============================] - 0s 980us/step - loss: 0.4155 - accuracy: 0.8219
Epoch 9/100
250/250 [==============================] - 0s 969us/step - loss: 0.4112 - accuracy: 0.8232
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4066 - ac

In [31]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [32]:
y_pred = ann.predict(x_test)
y_pred =(y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
print(cm)
accuracy_score(y_pred, y_test)

[[1516  189]
 [  79  216]]


0.866