In [0]:
arr1 = [25,56,12,85,34,75]
arr2 = [42,3,86,32,856,46]

In [0]:
import numpy as np


In [0]:
Narr = np.linspace(0, 100, 6)

In [0]:
Narr

array([  0.,  20.,  40.,  60.,  80., 100.])

In [0]:
complex(arr1)

TypeError: ignored

In [0]:
arr1 = np.array(arr1, dtype=complex)

In [0]:
arr1

array([25.+0.j, 56.+0.j, 12.+0.j, 85.+0.j, 34.+0.j, 75.+0.j])

In [0]:
arr1 = arr1.reshape(2,3)


In [0]:
arr1 

array([[25.+0.j, 56.+0.j, 12.+0.j],
       [85.+0.j, 34.+0.j, 75.+0.j]])

In [0]:
arr2 = np.array(arr2)

In [0]:
arr2 = np.reshape(2,3)

ValueError: ignored

In [0]:
arr2.astype(complex)

array([ 42.+0.j,   3.+0.j,  86.+0.j,  32.+0.j, 856.+0.j,  46.+0.j])

In [0]:
arr2

array([ 42,   3,  86,  32, 856,  46])

In [0]:
arr2 = arr2.astype(complex)

In [0]:
arr2 = arr2.reshape(2,3)

In [0]:
(arr1 + arr2) * (arr1 - arr2)

array([[  -1139.+0.j,    3127.+0.j,   -7252.+0.j],
       [   6201.+0.j, -731580.+0.j,    3509.+0.j]])

In [0]:
(arr1 ** 2) - (arr2 ** 2)

array([[  -1139.+0.j,    3127.+0.j,   -7252.+0.j],
       [   6201.+0.j, -731580.+0.j,    3509.+0.j]])

In [0]:
import numpy as np
arr = np.arange(4)
arr.reshape(2,2)
print(arr.shape)

(4,)


In [0]:
arr

array([0, 1, 2, 3])

In [0]:
mat = np.arange(16).reshape(4,4)

In [0]:
mat = np.zeros(mat)

TypeError: ignored

In [0]:
np.zeros(16)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
m1 = np.zeros(16).reshape(4,4)

In [0]:
np.diag([4,5,6], 1)

array([[0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6],
       [0, 0, 0, 0]])

In [0]:
arr= np.arange(11)

In [0]:
arr > 6

array([False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [0]:
a = arr[arr>6]

In [0]:
a[a<10] * -1

array([-7, -8, -9])

In [0]:
 
import numpy as np
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 
 


In [0]:
mat.itemsize

12

In [0]:
mat.itemset(1)

IndexError: ignored

In [0]:
for i in range(len(mat)):
  if (mat[i][0] == arr[i]):
    print(mat[i][1])

A
C


In [21]:
 
import numpy as np
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
mat.argsort(axis=0)

array([[0, 1, 1],
       [1, 2, 0],
       [2, 0, 2]])

In [23]:
mat[mat.argsort(axis=0)][1]

array([[ 5,  4,  2],
       [56, 12,  4],
       [ 1, 21,  3]])

In [30]:
   
import numpy as np
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
 
print(np.sort(arr)[6:])

[ 45  50  90 590]


In [39]:
 
arr = np.array([10,55,22,3,6,44,9,54])
nearest_to = 50
 
arr[np.abs(arr - nearest_to).argmin()]

54