In [0]:
 
import numpy as np
mat = np.array([[10,5,9],
                [2,20,6],
                [8,3,30]]).reshape(3,3)


In [0]:
N1 = mat[0].max()
N2 = mat[1].max()
N3 = mat[2].max()

In [0]:
mat[np.tril_indices(3, -1)] = mat[np.tril_indices(3, -1)] + N3

In [38]:
mat

array([[10,  5,  9],
       [32, 20,  6],
       [38, 33, 30]])

In [0]:
mat[np.mask_indices(3, np.triu, 1)] = mat[np.mask_indices(3, np.triu, 1)] + N1

In [40]:
mat

array([[10, 15, 19],
       [32, 20, 16],
       [38, 33, 30]])

In [0]:
mat[np.diag_indices(3)] = mat[np.diag_indices(3)] + N2

In [43]:
mat

array([[30, 15, 19],
       [32, 40, 16],
       [38, 33, 50]])

In [53]:
import numpy as np
arr = np.arange(9, dtype = "float").reshape(3,3)
ind1 = np.array([[1,2],[0,1]])
ind2 = np.array([[0,2],[1,2]])
print(arr[ind1, ind2])

[[3. 8.]
 [1. 5.]]
