In [3]:
pip install quandl

     |████████████████████████████████| 61kB 9.7MB/s 
     |████████████████████████████████| 61kB 9.3MB/s 
     |████████████████████████████████| 2.3MB 26.8MB/s 
  Created wheel for inflection: filename=inflection-0.3.1-cp36-none-any.whl size=6076 sha256=0c1fdfc72a13a7212f10ab865c66d9b66befa1c0b55ef03f9ee1946250ec9c71
  Stored in directory: /root/.cache/pip/wheels/9f/5a/d3/6fc3bf6516d2a3eb7e18f9f28b472110b59325f3f258fe9211
Successfully built inflection
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
  Found existing installation: more-itertools 7.2.0
    Uninstalling more-itertools-7.2.0:
      Successfully uninstalled more-itertools-7.2.0


In [0]:
import quandl
import numpy as np
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [2]:
df = quandl.get('WIKI/AMZN')
df.head()

Open   High    Low  ...  Adj. Low  Adj. Close  Adj. Volume
Date                             ...                                   
1997-05-16  22.38  23.75  20.50  ...  1.708333    1.729167   14700000.0
1997-05-19  20.50  21.25  19.50  ...  1.625000    1.708333    6106800.0
1997-05-20  20.75  21.00  19.63  ...  1.635833    1.635833    5467200.0
1997-05-21  19.25  19.75  16.50  ...  1.375000    1.427500   18853200.0
1997-05-22  17.25  17.38  15.75  ...  1.312500    1.395833   11776800.0

[5 rows x 12 columns]

In [4]:
df = df[['Adj. Close']]
df.head()

Adj. Close
Date                  
1997-05-16    1.729167
1997-05-19    1.708333
1997-05-20    1.635833
1997-05-21    1.427500
1997-05-22    1.395833

In [8]:
forecast_out = 30
df['Prediction'] = df[['Adj. Close']].shift(-forecast_out)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [9]:
df.tail()

Adj. Close  Prediction
Date                              
2018-03-21     1581.86         NaN
2018-03-22     1544.10         NaN
2018-03-23     1495.56         NaN
2018-03-26     1555.86         NaN
2018-03-27     1497.05         NaN

In [0]:
X = np.array(df.drop(['Prediction'],1))

In [20]:
X = X[:-forecast_out]
X

array([[   1.72916667],
       [   1.70833333],
       [   1.63583333],
       ...,
       [1350.47      ],
       [1338.99      ],
       [1386.23      ]])

In [21]:
y = np.array(df['Prediction'])
y = y[:-forecast_out]
y

array([1.54166667e+00, 1.51583333e+00, 1.58833333e+00, ...,
       1.49556000e+03, 1.55586000e+03, 1.49705000e+03])

In [0]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [24]:
svr = SVR(kernel= 'rbf', C=1e3, gamma=0.1)
svr.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [25]:
score = svr.score(x_test, y_test)
score

0.9646607995870807

In [26]:
x_forecast = np.array(df.drop(['Prediction'], 1)) [-forecast_out:]
x_forecast

array([[1414.51],
       [1451.05],
       [1461.76],
       [1448.69],
       [1468.35],
       [1482.92],
       [1484.76],
       [1500.  ],
       [1521.95],
       [1511.98],
       [1512.45],
       [1493.45],
       [1500.25],
       [1523.61],
       [1537.64],
       [1545.  ],
       [1551.86],
       [1578.89],
       [1598.39],
       [1588.18],
       [1591.  ],
       [1582.32],
       [1571.68],
       [1544.93],
       [1586.51],
       [1581.86],
       [1544.1 ],
       [1495.56],
       [1555.86],
       [1497.05]])

In [27]:
svm_prediction = svr.predict(x_forecast)
svm_prediction

array([1197.29582539, 1550.42368088,  683.0241704 , 1057.41779639,
        682.99144725,  682.99144725,  682.99144725,  682.99144725,
        682.99144725,  682.99144725,  682.99144725,  682.99144725,
        682.99144725,  682.99144725,  682.99144725,  682.99144725,
        682.99144725,  682.99144725,  682.99144725,  682.99144725,
        682.99144725,  682.99144725,  682.99144725,  682.99144725,
        682.99144725,  682.99144725,  682.99144725,  682.99144725,
        682.99144725,  682.99144725])